export enum SpendingTypes {
    GROCERY = 'GROCERY',
    BILLS = 'BILLS',
    SCHOOL = 'SCHOOL',
    HEALTH = 'HEALTH',
    TRANSPORTATION = 'TRANSPORTATION',
    CLOTHING = 'CLOTHING',
    ENTERTAINMENT = 'ENTERTAINMENT'
  }